title: Unofficial Button Plus documentation
description: Unofficial Documentation for Button Plus
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Button Plus site: https://button.plus
